SELECT E.FIRST_NAME || ' - ' || E.LAST_NAME AS "F and L",
CASE WHEN D.DEPARTMENT_NAME IS NULL THEN 'X'
ELSE D.DEPARTMENT_NAME END AS DEPARTMENT_NAME,
M.FIRST_NAME AS "MANAGER NAME",
'$' || TO_CHAR(E.SALARY, 'FM999,999,999.00') AS SALARY, MM.FIRST_NAME AS "MANAGER'S MANAGER'S NAME", MM.SALARY AS "MANAGER'S MANAGER'S SALARY"
FROM EMPLOYEES E, EMPLOYEES M, EMPLOYEES MM, DEPARTMENTS D
WHERE E.MANAGER_ID = M.EMPLOYEE_ID
AND M.MANAGER_ID = MM.EMPLOYEE_ID
AND E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND (MM.FIRST_NAME LIKE '%A%' OR MM.FIRST_NAME LIKE '%a%')
AND (REMAINDER(MM.SALARY,17) = 0);

