SELECT
SUBSTR(JOB_ID, 1, INSTR(JOB_ID, '_')-1) pref,
COUNT(*) count,
CASE
WHEN (SELECT COUNT(*) FROM EMPLOYEES WHERE JOB_ID LIKE SUBSTR(JOB_ID, 1, INSTR(JOB_ID, '_')-1) || '%') = 0
THEN 'N'
ELSE 'Y' END yn,
'$' || TO_CHAR(AVG(SALARY), 'FM999,999,999.00') avg_salary,
COUNT(CASE
WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2002 THEN 1
ELSE NULL END) cnt_2002

FROM EMPLOYEES
GROUP BY SUBSTR(JOB_ID, 1, INSTR(JOB_ID, '_')-1)
ORDER BY
CASE pref
WHEN 'IT' THEN 1
WHEN 'MK' THEN 2
ELSE 3
END,
LENGTH(AVG_SALARY) DESC, AVG_SALARY DESC;