SELECT
FIRST_NAME || ' ' || LAST_NAME "Full_Name",
'$' || TO_CHAR(TRIM(SALARY), 'FM999,999,999.00')  SALARY,
CASE
WHEN EMAIL IS NULL OR INSTR(EMAIL, '@') = 0 THEN 'INVALID MAIL'
ELSE EMAIL END AS EMAIL,
CASE WHEN MONTHS_BETWEEN(SYSDATE, HIRE_DATE) <= EXTRACT(MONTH FROM SYSDATE) THEN SALARY * (MONTHS_BETWEEN(SYSDATE,HIRE_DATE)-1)
ELSE (EXTRACT(MONTH FROM SYSDATE) - 1)*SALARY END AS SALARY_THIS_YEAR,
CASE
WHEN COMMISSION_PCT IS NULL THEN 'No Com'
ELSE TO_CHAR(COMMISSION_PCT) END AS COMMISSION_PCT
FROM EMPLOYEES

WHERE (DEPARTMENT_ID = 50 OR (SYSDATE - HIRE_DATE >= 365 * 5))
AND PHONE_NUMBER LIKE '515%'
AND SALARY BETWEEN 5000 AND 10000
AND MANAGER_ID IS NOT NULL
AND JOB_ID NOT IN ('IT_PROG', 'PU_CLERK')
GROUP BY EMPLOYEES.EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, SALARY, COMMISSION_PCT, HIRE_DATE
ORDER BY LENGTH(SALARY) DESC, SALARY DESC, HIRE_DATE;