WINGS_TO_FLY = 2
STAMINA_TO_FLY = 80
FLY_USED_STAMINA = 4
FLY_SPEED = 8

LEGS_TO_RUN = 2
STAMINA_TO_RUN = 60
RUN_USED_STAMINA = 4
RUN_SPEED = 8

LEGS_TO_WALK = 2
STAMINA_TO_WALK = 40
WALK_USED_STAMINA = 2
WALK_SPEED = 4

LEGS_TO_HOP = 1
STAMINA_TO_HOP = 20
HOP_USED_STAMINA = 2
HOP_SPEED = 3

CRAWLING_SPEED = 1
CRAWLING_USED_STAMINA = 1
